#!/usr/bin/env python3
# -*- coding: utf-8 -*-

NEW_LINE              = "\n"
DEFAULT_USERNAME      = "username"
TRYING_CONNECTION     = "trying connection"
CAN_NOT_CONNECT       = "can not connect"
CONNECTION_SUCCESS    = "connection successful"
YOUR_NAME             = "Your name please"
DISCONNECTED_FROM_SERVER = "Disconnect from server"
USER                  = "User "

SERVER_STARTED        = "server started: ctl + c to exit or exit to exit"

SERVER_STOPPED        = "server stopped"
NEW_CLIENT            = "new client"
WELCOME_CLIENT        = "welcome user \n"
CLIENT_INPUT          = "client input received"
CLIENT_INVALID        = "client invalid"
CLIENT_DISCONNECT     = "server disconnected"
CLIENT_DISCONNECT_ERR = "server disconnect error"
CLIENT_ALREADY_IN     = "you are already in the system"
CLIENT_EXISTS         = "name exists"
INPUT_INVALID         = "input invalid"
UNKNOWN_COMMAND       = "command invalid Type - HELP"
ROOMS                 = "rooms"
CLIENTS               = "clients"
NAME                  = "name"
SOCKET                = "socket"

ROOMS_AVAILABLE_TITLE = "Available rooms \n"
NO_ROOMS_TITLE        = "Sorry, no rooms "
INVALID_ROOM_NAME     = "invalid room name"
ROOM_DOES_NOT_EXIST   = "room does not exist"
ROOM_MEMBERS          = "room members \n"
ROOM_ADDED            = "new room added"
ALREADY_MEMBER        = "you are already member"
NEW_MEMBER_JOINED     = "new member joined in room"
MEMBER_LEFT           = "one member left the room"
YOU_LEFT_ROOM         = "you left the room"
MEMBERSHIP_GRANTED    = "Membership granted to the room"
NOT_MEMBER            = "you are not member"
INVALID_MESSAGE_FORMAT = "invalid message format"
EXIT_SUCCESSFUL       = "'\n exit successfull"

USER = "USER"
LIRO = "LIRO"
LIME = "LIME"
ROOM = "ROOM"
JOIN = "JOIN"
LEVE = "LEVE"
SEND = "SEND"
HELP = "HELP"
EXIT = "EXIT"
HELP_MESSAGE = "\n commands \n liro - list all rooms \n lime + room name - list all members \n room + room name - create new room \n join + room name - join the room \n leve + room name - leave the room \n send + room name + message - send given message to given room \n help - to see help \n exit - to exit \n"